runtime: python27
api_version: 1
threadsafe: true

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: zscoresleep:us-east1:zscore-sql-1

libraries:
- name: MySQLdb
  version: "1.2.5"
- name: numpy
  version: "1.6.1"

env_variables:
  DEBUG: "false"
  ADMINS: "zscore-owner@mit.edu"

handlers:
- url: /.*
  script: zscore.wsgi.application
  secure: always
