# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-29 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0009_auto_20180129_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialsleep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
